package agenda;

import java.awt.EventQueue;
import java.awt.FlowLayout;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import material.MaterialUIConfig;

/**
 *
 * @author alberto
 */
public class AgendaInterfaz extends JFrame {

	private static final long serialVersionUID = 1L;
	// test
	private Object[] panels;
	// Interface
    private JButton deleteContact;
    private JButton importButton;
    private JScrollPane jScrollPane1;
    private JList listContacts;
    private JButton loadContacts;
    private JButton modifyContact;
    private JButton newContact;
    private JButton saveContacts;
    private javax.swing.JTextField searchField;
    // End of variables declaration                   


    /**
     * Creates new form NewApplication
     * @param agendaLogica 
     */
    public AgendaInterfaz(AgendaLogica agendaLogica) {

        System.out.println(getClass().getClassLoader().getResource("images/contact.png"));
        // get our images
        Icon pingImage = new ImageIcon(getClass().getClassLoader().getResource("images/contact.png"));
        Icon tracerouteImage = new ImageIcon(getClass().getClassLoader().getResource("images/contact.png"));
        Icon netstatImage = new ImageIcon(getClass().getClassLoader().getResource("images/contact.png"));

        // add the images to jlabels with text
        JLabel pingLabel = new JLabel("Contacto1", pingImage, JLabel.LEFT);
        JLabel tracerouteLabel = new JLabel("Contacto2", tracerouteImage, JLabel.LEFT);
        JLabel netstatLabel = new JLabel("Contacto3", netstatImage, JLabel.LEFT);

        // create the corresponding panels
        JPanel pingPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JPanel traceroutePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JPanel netstatPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));

        // add the labels onto the panels
        pingPanel.add(pingLabel);
        traceroutePanel.add(tracerouteLabel);
        netstatPanel.add(netstatLabel);

        // create a panel array
        panels = new Object[]{pingPanel, traceroutePanel, netstatPanel};

        MaterialUIConfig.configureUI();

        initComponents();

        listContacts.setListData(panels);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newContact = new JButton();
        modifyContact = new JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listContacts = new javax.swing.JList();
        deleteContact = new JButton();
        searchField = new javax.swing.JTextField();
        importButton = new JButton();
        saveContacts = new JButton();
        loadContacts = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda telefónica");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        newContact.setText("Nuevo contacto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(newContact, gridBagConstraints);

        modifyContact.setText("Modificar contacto");
        modifyContact.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(modifyContact, gridBagConstraints);

        listContacts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listContacts.setCellRenderer(new ContactoCellRender());
        listContacts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listContactsFocusLost(evt);
            }
        });
        listContacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listContactsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listContacts);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        deleteContact.setText("Borrar contacto");
        deleteContact.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(deleteContact, gridBagConstraints);

        searchField.setText("Buscar...");
        searchField.setToolTipText("Busca en la agenda");
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(searchField, gridBagConstraints);

        importButton.setText("Importar / Exportar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(importButton, gridBagConstraints);

        saveContacts.setText("Guardar agenda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(saveContacts, gridBagConstraints);

        loadContacts.setText("Cargar agenda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(loadContacts, gridBagConstraints);

        pack();
    }// </editor-fold>                        

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (searchField.getText().equals("Buscar...")) {
            searchField.setText("");
        }
    }                                        

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {                                      
        if (searchField.getText().equals("")) {
            searchField.setText("Buscar...");
        }
    }                                     

    private void listContactsMouseClicked(java.awt.event.MouseEvent evt) {                                          
        modifyContact.setEnabled(true);
        deleteContact.setEnabled(true);
    }                                         

    private void listContactsFocusLost(java.awt.event.FocusEvent evt) {                                       
        // aqui algo raro
        //modifyContact.setEnabled(false);
        //deleteContact.setEnabled(false);
        //listContacts.clearSelection();
    }                                      
}
